name: sh

on:
  schedule:
    - cron: "0 0 * * *" # run at 00:00 UTC everyday
  workflow_dispatch: # run on manual trigger
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: run shell script
        run: sh ./scripts/sample.sh